### ISSUE TITLE
Suggestion for eliminating allocation

### ISSUE THREAD

**Issue by elimisteve** [woodsbury/decimal128#8]
Your implementation looks good!

One little thing: at https://github.com/woodsbury/decimal128/blame/1f851cce64708d0b621f70486bf3985fe507f2d3/compare.go#L1035C12-L1035C12 , could you replace `Decimal{}` with a global constant called `Zero` or similar? I'd send a PR but I'm not sure what you'd prefer to call said constant.

Thanks!

**Comment by woodsbury** [comment]
`Decimal{}` won't cause any allocations here, it's just referencing the `Decimal` types "zero value" (what Go calls the value a type gets when it isn't explicitly initialised with something else). The zero value for a `Decimal` is, conveniently, the number zero.

There are a number of ways that zero (and most other values) can be represented in decimal128. That check isn't strictly necessary, but the code assumes that zeros will usually be represented by that zero value so it's a little bit of a short circuit to the other code after it for the common case.

There hasn't been a need to define constants for values like zero because the compiler will do a good job of generating them for you or constructing them is trivially quick, either by just declaring the variable without defining it to get zero or using the functions like `FromInt64` and `New`. The library does provide constants for values like pi and e though, via constructor functions, since those can be trickier to get right. None of those functions will allocate, and the values they return will be stored on the stack (unless you explicitly put them on the heap by taking their address or assigning them to a pointer).

Generally speaking functions in this library don't allocate. There are obvious exceptions - functions that need to return strings or byte slices need to allocate those - but the functions that just operate on the actual `Decimal` type typically don't cause any allocations. You can test out whether a function allocates or not using the `testing.AllocsPerRun()` function in the standard library, for example: https://play.golang.com/p/rZRVODFn7W4

**Comment by elimisteve** [comment]
> `Decimal{}` won't cause any allocations here, it's just referencing the Decimal types "zero value"

In Go, zero values are allocated just like other values are; after all, those values need to be stored somewhere, zero or otherwise! See https://play.golang.com/p/TdmsmeuKVQW .

Running `Decimal{}` does cause a `Decimal` to be allocated somewhere in memory, but I did forget that the Go compiler tries to cache constants and immutable, hardcoded values so that said values don't have to be _re_-allocated _every time a function is run_, or for every iteration of a loop. I think that must be what's happening here, or else `x := 5` would allocate per run just like I initially, incorrectly thought that `Decimal{}` would allocate per run.

Anyway, this library of yours looks excellent :slightly_smiling_face: . I plan to use it when I am further along in implementing a new programming language, Phi, which I'm transpiling to Go. That way we can live in a world where 0.1 + 0.2 == 0.3 -- imagine that! :tada:
